language: any
services:
  - docker
branches:
  only:
    - master
env:
  - RELEASE=false
pre_install: 
  - # Starting build for cszheng/ShooterMcGavinBot...
install:
  - # Building docker image...
  - docker build -t cszheng/shooter-mcgavin-bot .
script:
  - # Running tests...
  - docker run -e DOTNETCORE_ENVIRONMENT=$DOTNETCORE_ENVIRONMENT -e DISCORDBOT_TOKEN=$DISCORDBOT_TOKEN cszheng/shooter-mcgavin-bot ./test.sh
after_success:
  - if [ "$RELEASE" == "false" ]; then
      exit 0;
    fi
  - # Creating version number...
  - export BUILD_VERSION=v0.1.0.$TRAVIS_BUILD_NUMBER
  - # Pushing build tag to github...  
  - export REMOTE_URL=https://$GIT_OAUTH_USER:$GIT_OAUTH_TOKEN@$GIT_REMOTE_URL
  - git remote rm origin
  - git remote add origin $REMOTE_URL  
  - git tag $BUILD_VERSION -am "Generated tag from TravisCI build $BUILD_VERSION"
  - git push origin $TRAVIS_BRANCH --tags
  - # Pushing docker image to dockerhub...
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push cszheng/shooter-mcgavin-bot;
    fi