language: any
services:
- docker
branches:
  only:
  - master
env: 
  - RELEASE=true 
  - RELEASE_MAJOR=0 
  - RELEASE_MINOR=1 
  - RELEASE_BUGFIXES=0
before_install:
  # unencrypt secrets, extract, and move them
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
  - tar -xvf secrets.tar.gz
  - cp -f secrets/github_credentials.sh ./github_credentials.sh
  # add permissions to secrets shell scripts
  - chmod +x github-credentials.sh
  # add permissions to non-secrets scripts
  - chmod +x travis_scripts/install/install.sh
  - chmod +x travis_scripts/script/script.sh
  - chmod +x travis_scripts/after_success/after_success.sh
  - chmod +x travis_scripts/release_git.sh
  # run secrets scripts
  - ./github_credentials.sh
install:
  - ./travis_scripts/install/install.sh
script:
  - ./travis_scripts/script/script.sh
after_success:
  - ./travis_scripts/after_success/after_success.sh
after_script:
  #remove secrets
  - rm -rf secrets.tar.gz
  - rm -rf secrets
  - rm -rf ./github-credentials.sh
  - ls -al