#!/bin/bash
#create a release tag for the current build
RELEASE_TAG=$1
DOCKER_USER=$2
DOCKER_PASSWORD=$3
DOCKER_URL=$4
DOCKER_IMAGE=$5

REGISTERY_URL=https://$DOCKER_URL    

docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $REGISTERY_URL
docker tag $DOCKER_USER/$DOCKER_IMAGE $DOCKER_USER/$DOCKER_IMAGE:$RELEASE_TAG
docker push $DOCKER_USER/$DOCKER_IMAGE
docker logout