#!/bin/bash
echo "docker run -e DOTNETCORE_ENVIRONMENT=[DOTNETCORE_ENVIRONMENT] cszheng/[DOCKER_IMAGE] ./test.sh"
docker run -e DOTNETCORE_ENVIRONMENT=$DOTNETCORE_ENVIRONMENT cszheng/$DOCKER_IMAGE ./test.sh