#!/bin/bash
echo "docker run -e DOTNETCORE_ENVIRONMENT=[DOTNETCORE_ENVIRONMENT] -e DISCORDBOT_TOKEN=[DISCORDBOT_TOKEN] cszheng/[DOCKER_IMAGE] ./test.sh"
docker run -e DOTNETCORE_ENVIRONMENT=$DOTNETCORE_ENVIRONMENT -e DISCORDBOT_TOKEN=$DISCORDBOT_TOKEN cszheng/$DOCKER_IMAGE ./test.sh